name: "Rajeev Ranjan Chaurasia"
tagline: "Software Engineer"
bio: "I’m a Software Engineering graduate student at San Jose State University, currently a Software Engineering Intern at NVIDIA working on developer infrastructure for Omniverse simulation pipelines. Previously, I built enterprise accounting and payment systems as a Software Engineer at Tekion Corp. I’m passionate about scalable backend systems and trustworthy developer infrastructure."
email: "rajeevchaurasia.dev@gmail.com"
github: "https://github.com/rajeev-chaurasia"
linkedin: "https://www.linkedin.com/in/rajeev-chaurasia/"
profileImage: "/images/profile.jpg"
resume: "/files/resume.pdf"
resumeUrl: "https://drive.google.com/uc?export=download&id=1ho2aaGgYm4nB7i6vvIRJapWc0rZtwVqt"
